version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install aws-sam-cli
      - npm install -g yarn

  pre_build:
    commands:
      - echo "Installing frontend dependencies at root..."
      - npm install --force

  build:
    commands:
      - echo "Building React frontend..."
      - npm run build

      - echo "Building backend (Lambdas) with AWS SAM..."
      - sam build --template-file backend/template.yaml

  post_build:
    commands:
      - echo "Build artifacts generated and ready for deployment."

artifacts:
  files:
    - '**/*'
  base-directory: .
  discard-paths: no
