version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install -g npm@latest

  pre_build:
    commands:
      - echo Starting pre-build phase...
      - echo "Current directory structure:"
      - ls -la
      # Install dependencies at the root level
      - if [ -f "package.json" ]; then npm install; fi

  build:
    commands:
      - echo Starting build phase...
      # Build at root level
      - if [ -f "package.json" ]; then npm run build || echo "Build command failed but continuing"; fi

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    # Include all files
    - '**/*'
  discard-paths: no
  base-directory: '.'

cache:
  paths:
    - 'node_modules/**/*'
