AWSTemplateFormatVersion: '2010-09-09'
Description: 'HR Management System Backend Resources'

Parameters:
  S3DocumentsBucketName:
    Type: String
    Description: Name of the existing S3 bucket for document storage
    Default: hrms-document-storage-bucket
  
  CognitoUserPoolId:
    Type: String
    Description: ID of the Cognito User Pool
    Default: us-east-1_dshoL8wrB
  
  CognitoAppClientId:
    Type: String
    Description: ID of the Cognito App Client
    Default: 6uvfbks36bdpqoiqetb4r1glhk

# No S3 bucket resource defined here since it already exists

Outputs:
  DocumentsBucketName:
    Description: Name of the S3 bucket for document storage
    Value: !Ref S3DocumentsBucketName
  
  CognitoUserPoolId:
    Description: ID of the Cognito User Pool
    Value: !Ref CognitoUserPoolId
  
  CognitoAppClientId:
    Description: ID of the Cognito App Client
    Value: !Ref CognitoAppClientId
